<?php


namespace Common\JsonRpc;

/**
 * Test class for Request.
 * Generated by PHPUnit on 2011-12-28 at 14:51:17.
 */
class RequestTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var Request
   */
  protected $object;


  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Request;
  }


  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }


  /**
   * testIs_notification().
   */
  public function testIs_notification()
  {
    $this->object->id = null;
    $this->assertTrue( $this->object->is_notification() );
    $this->object->id = 1;
    $this->assertFalse( $this->object->is_notification() );
  }
}

?>
