<?php

require_once "FakeAuthenticator.php";

/**
 * Test class for BasicAuth.
 * Generated by PHPUnit on 2011-12-28 at 14:54:46.
 */
class BasicAuthTest extends PHPUnit_Framework_TestCase
{

  /**
   * @var \Common\Middleware\Http\BasicAuth
   */
  protected $object;


  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new \Common\Middleware\Http\BasicAuth( true, new FakeAuthenticator() );
  }


  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }


  /**
   * Test basic authentication
   */
  public function testCall()
  {
    $request = new \Common\Middleware\Request();
    $request->httpRequest = new \Common\Middleware\Http\Request();
    $response = new \Common\Middleware\Response();
    $request->httpRequest->authentication_user = 'user';
    $request->httpRequest->authentication_pass = 'right';
    $this->object->call( $request, $response );
    $this->assertTrue( $request->httpRequest->authenticated );
    $this->assertFalse( $response->fullfilled );
    $request->httpRequest->authentication_pass = 'wrong';
    $this->object->call( $request, $response );
    $this->assertFalse( $request->httpRequest->authenticated );
    $this->assertTrue( $response->fullfilled );
    $this->assertEquals( 401, $response->httpResponse->code );
  }

}
